blueprint:
  name: ZHA - Tuya 6-Button Scene Switch
  description: Automate your Tuya 6-Button Scene Switch using ZHA events.
  domain: automation
  input:
    tuya_6button_scene_switch:
      name: Tuya 6-Button Scene Switch
      description: Tuya 6-Button Scene Switch to use
      selector:
        device:
          integration: mqtt
          manufacturer: _TZ3000_iszegwpd
          model: TS0046
    button_one_single_press:
      name: Single Press
      description: Action to run on button 1 single press
      default: []
      selector:
        action: {}
    button_one_double_press:
      name: Double Press
      description: Action to run on button 1 double press
      default: []
      selector:
        action: {}
    button_two_single_press:
      name: Single Press
      description: Action to run on button 2 single press
      default: []
      selector:
        action: {}
    button_two_double_press:
      name: Double Press
      description: Action to run on button 2 double press
      default: []
      selector:
        action: {}
    button_three_single_press:
      name: Single Press
      description: Action to run on button 3 single press
      default: []
      selector:
        action: {}
    button_three_double_press:
      name: Double Press
      description: Action to run on button 3 double press
      default: []
      selector:
        action: {}
    button_four_single_press:
      name: Single Press
      description: Action to run on button 4 single press
      default: []
      selector:
        action: {}
    button_four_double_press:
      name: Double Press
      description: Action to run on button 4 double press
      default: []
      selector:
        action: {}
    button_five_single_press:
      name: Single Press
      description: Action to run on button 5 long press
      default: []
      selector:
         action: {}
    button_five_double_press:
      name: Double Press
      description: Action to run on button 5 double press
      default: []
      selector:
        action: {}
    button_six_single_press:
      name: Single Press
      description: Action to run on button 6 long press
      default: []
      selector:
         action: {}
    button_six_double_press:
      name: Double Press
      description: Action to run on button 6 double press
      default: []
      selector:
        action: {}
mode: restart
max_exceeded: silent
trigger:
- platform: event
  event_type: mqtt_event
  event_data:
    device_id: !input 'tuya_6button_scene_switch'
action:
- variables:
    command: '{{ trigger.event.data.command }}'   
    endpoint_id: '{{ trigger.event.data.endpoint_id }}'
- choose:
  - conditions: "{{ command == 'remote_button_short_press' }}"
    sequence:
    - choose:
      - conditions: '{{ endpoint_id == 1 }}'
        sequence: !input 'button_one_short_press'
      - conditions: '{{ endpoint_id == 2 }}'
        sequence: !input 'button_two_short_press'
      - conditions: '{{ endpoint_id == 3 }}'
        sequence: !input 'button_three_short_press'
      - conditions: '{{ endpoint_id == 4 }}'
        sequence: !input 'button_four_short_press'
      - conditions: '{{ endpoint_id == 5 }}'
        sequence: !input 'button_five_short_press'
      - conditions: '{{ endpoint_id == 6 }}'
        sequence: !input 'button_six_short_press'
  - conditions: "{{ command == 'remote_button_double_press' }}"
    sequence:
    - choose:
      - conditions: '{{ endpoint_id == 1 }}'
        sequence: !input 'button_one_double_press'
      - conditions: '{{ endpoint_id == 2 }}'
        sequence: !input 'button_two_double_press'
      - conditions: '{{ endpoint_id == 3 }}'
        sequence: !input 'button_three_double_press'
      - conditions: '{{ endpoint_id == 4 }}'
        sequence: !input 'button_four_double_press'
      - conditions: '{{ endpoint_id == 5 }}'
        sequence: !input 'button_five_double_press'
      - conditions: '{{ endpoint_id == 6 }}'
        sequence: !input 'button_six_double_press'


